#!/bin/bash
#
# QN Code Assistant - Installer Builder
# Generates install.sh with baked-in SHA-256 hashes for integrity verification.
#
# Usage: ./build-installer.sh
#
# After making code changes, run this to regenerate install.sh with updated hashes.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALLER="${SCRIPT_DIR}/install.sh"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

# Files to include in integrity verification (relative to project root)
PROJECT_FILES=(
    "app.py"
    "static/js/app.js"
    "static/css/style.css"
    "templates/index.html"
    "templates/login.html"
    "requirements.txt"
    "static/manifest.json"
    "static/sw.js"
    "static/icon.svg"
    "apache-proxy.conf"
    "maintenance.sh"
    "start.sh"
    "qn-code-assistant.service"
)

# Determine sha256 command
if command -v sha256sum &> /dev/null; then
    SHA_CMD="sha256sum"
elif command -v shasum &> /dev/null; then
    SHA_CMD="shasum -a 256"
else
    echo -e "${RED}Error: Neither sha256sum nor shasum found.${NC}" >&2
    exit 1
fi

echo -e "${GREEN}Building QN Code Assistant installer...${NC}"
echo ""

# Compute hashes for project files
declare -A HASHES
MISSING=0

for file in "${PROJECT_FILES[@]}"; do
    filepath="${SCRIPT_DIR}/${file}"
    if [[ ! -f "${filepath}" ]]; then
        echo -e "${RED}Error: Missing file: ${file}${NC}" >&2
        MISSING=1
        continue
    fi
    hash="$($SHA_CMD "${filepath}" | awk '{print $1}')"
    HASHES["${file}"]="${hash}"
    echo -e "  ${file}: ${hash}"
done

# Compute aggregate hash for vendor/ directory
VENDOR_DIR="${SCRIPT_DIR}/vendor"
if [[ ! -d "${VENDOR_DIR}" ]]; then
    echo -e "${RED}Error: vendor/ directory not found. Run: pip install --target=vendor/ flask flask-socketio${NC}" >&2
    MISSING=1
else
    VENDOR_FILE_COUNT="$(find "${VENDOR_DIR}" -type f -not -path '*/__pycache__/*' | wc -l)"
    VENDOR_HASH="$(cd "${SCRIPT_DIR}" && find vendor/ -type f -not -path '*/__pycache__/*' -print0 | sort -z | xargs -0 $SHA_CMD | $SHA_CMD | awk '{print $1}')"
    echo -e "  vendor/ (${VENDOR_FILE_COUNT} files): ${VENDOR_HASH}"
fi

# Compute aggregate hash for static/js/ace/ directory
ACE_DIR="${SCRIPT_DIR}/static/js/ace"
if [[ ! -d "${ACE_DIR}" ]]; then
    echo -e "${RED}Error: static/js/ace/ directory not found.${NC}" >&2
    MISSING=1
else
    ACE_FILE_COUNT="$(find "${ACE_DIR}" -type f -not -path '*/__pycache__/*' | wc -l)"
    ACE_HASH="$(cd "${SCRIPT_DIR}" && find static/js/ace/ -type f -not -path '*/__pycache__/*' -print0 | sort -z | xargs -0 $SHA_CMD | $SHA_CMD | awk '{print $1}')"
    echo -e "  static/js/ace/ (${ACE_FILE_COUNT} files): ${ACE_HASH}"
fi

if [[ "${MISSING}" -eq 1 ]]; then
    echo -e "${RED}Aborting: one or more project files are missing.${NC}" >&2
    exit 1
fi

echo ""
echo -e "${YELLOW}Generating ${INSTALLER}...${NC}"

# Get current version from app.py
VERSION=$(grep -oP "VERSION\s*=\s*['\"]([^'\"]+)['\"]" "${SCRIPT_DIR}/app.py" | head -1 | grep -oP "['\"][^'\"]+['\"]" | tr -d "'\"" || echo "unknown")

# Generate the installer script
cat > "${INSTALLER}" << 'INSTALLER_HEADER'
#!/bin/bash
#
# QN Code Assistant - Secure Self-Verifying Installer
#
# Self-contained installer with vendored Python dependencies.
# Only requires Python 3.10+ on the target system. No pip, no venv, no internet.
#
# Usage:
#   ./install.sh              Install (verify + setup)
#   ./install.sh --verify-only    Only verify file integrity
#   ./install.sh --uninstall      Remove service and cleanup
#
# Generated by build-installer.sh -- DO NOT EDIT MANUALLY
#

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

INSTALLER_HEADER

# Inject the version
cat >> "${INSTALLER}" << EOF
VERSION="${VERSION}"
EOF

# Inject the hash map
cat >> "${INSTALLER}" << 'HASH_MAP_START'

# SHA-256 hashes baked at build time
declare -A FILE_HASHES=(
HASH_MAP_START

# Write each hash entry
for file in "${PROJECT_FILES[@]}"; do
    printf '    ["%s"]="%s"\n' "${file}" "${HASHES[${file}]}" >> "${INSTALLER}"
done

cat >> "${INSTALLER}" << 'HASH_MAP_END'
)

HASH_MAP_END

# Inject vendor hash and ace hash
cat >> "${INSTALLER}" << EOF
VENDOR_HASH="${VENDOR_HASH}"
VENDOR_FILE_COUNT="${VENDOR_FILE_COUNT}"
ACE_HASH="${ACE_HASH}"
ACE_FILE_COUNT="${ACE_FILE_COUNT}"
EOF

# Now write the rest of the installer logic
cat >> "${INSTALLER}" << 'INSTALLER_BODY'

NONINTERACTIVE=0

# -------------------------------------------------------------------
# Utility functions
# -------------------------------------------------------------------

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${CYAN}[STEP]${NC} ${BOLD}$1${NC}"
}

# Determine available sha256 command
detect_sha_cmd() {
    if command -v sha256sum &> /dev/null; then
        echo "sha256sum"
    elif command -v shasum &> /dev/null; then
        echo "shasum -a 256"
    else
        log_error "Neither sha256sum nor shasum found. Cannot verify integrity."
        exit 1
    fi
}

# -------------------------------------------------------------------
# Integrity verification
# -------------------------------------------------------------------

verify_integrity() {
    local sha_cmd
    sha_cmd="$(detect_sha_cmd)"
    local failed=0
    local checked=0
    local tampered_files=()

    echo ""
    echo -e "${BOLD}========================================${NC}"
    echo -e "${BOLD}  File Integrity Verification${NC}"
    echo -e "${BOLD}========================================${NC}"
    echo ""

    # Verify individual project files
    for file in "${!FILE_HASHES[@]}"; do
        local expected="${FILE_HASHES[${file}]}"
        local filepath="${INSTALL_DIR}/${file}"

        if [[ ! -f "${filepath}" ]]; then
            log_error "Missing file: ${file}"
            tampered_files+=("${file} (MISSING)")
            failed=1
            continue
        fi

        local actual
        actual="$($sha_cmd "${filepath}" | awk '{print $1}')"

        if [[ "${actual}" != "${expected}" ]]; then
            log_error "Hash mismatch: ${file}"
            echo "         Expected: ${expected}"
            echo "         Actual:   ${actual}"
            tampered_files+=("${file}")
            failed=1
        else
            log_info "Verified: ${file}"
        fi

        checked=$((checked + 1))
    done

    # Verify vendor/ directory
    local vendor_dir="${INSTALL_DIR}/vendor"
    if [[ ! -d "${vendor_dir}" ]]; then
        log_error "Missing directory: vendor/"
        tampered_files+=("vendor/ (MISSING)")
        failed=1
    else
        local actual_count
        actual_count="$(find "${vendor_dir}" -type f -not -path '*/__pycache__/*' | wc -l)"
        local actual_hash
        actual_hash="$(cd "${INSTALL_DIR}" && find vendor/ -type f -not -path '*/__pycache__/*' -print0 | sort -z | xargs -0 $sha_cmd | $sha_cmd | awk '{print $1}')"

        if [[ "${actual_hash}" != "${VENDOR_HASH}" ]]; then
            log_error "Hash mismatch: vendor/ (${actual_count} files)"
            echo "         Expected: ${VENDOR_HASH}"
            echo "         Actual:   ${actual_hash}"
            tampered_files+=("vendor/")
            failed=1
        else
            log_info "Verified: vendor/ (${actual_count} files)"
        fi
        checked=$((checked + 1))
    fi

    # Verify static/js/ace/ directory
    local ace_dir="${INSTALL_DIR}/static/js/ace"
    if [[ ! -d "${ace_dir}" ]]; then
        log_error "Missing directory: static/js/ace/"
        tampered_files+=("static/js/ace/ (MISSING)")
        failed=1
    else
        local ace_actual_count
        ace_actual_count="$(find "${ace_dir}" -type f -not -path '*/__pycache__/*' | wc -l)"
        local ace_actual_hash
        ace_actual_hash="$(cd "${INSTALL_DIR}" && find static/js/ace/ -type f -not -path '*/__pycache__/*' -print0 | sort -z | xargs -0 $sha_cmd | $sha_cmd | awk '{print $1}')"

        if [[ "${ace_actual_hash}" != "${ACE_HASH}" ]]; then
            log_error "Hash mismatch: static/js/ace/ (${ace_actual_count} files)"
            echo "         Expected: ${ACE_HASH}"
            echo "         Actual:   ${ace_actual_hash}"
            tampered_files+=("static/js/ace/")
            failed=1
        else
            log_info "Verified: static/js/ace/ (${ace_actual_count} files)"
        fi
        checked=$((checked + 1))
    fi

    echo ""

    if [[ "${failed}" -eq 1 ]]; then
        echo -e "${RED}${BOLD}========================================${NC}"
        echo -e "${RED}${BOLD}  INTEGRITY CHECK FAILED${NC}"
        echo -e "${RED}${BOLD}========================================${NC}"
        echo ""
        echo -e "${RED}The following files have been tampered with or are missing:${NC}"
        for tf in "${tampered_files[@]}"; do
            echo -e "  ${RED}- ${tf}${NC}"
        done
        echo ""
        echo -e "${RED}Installation aborted. Files do not match the expected checksums.${NC}"
        echo -e "${RED}Re-obtain the original project files before installing.${NC}"
        return 1
    else
        echo -e "${GREEN}${BOLD}========================================${NC}"
        echo -e "${GREEN}${BOLD}  ALL ${checked} ITEMS VERIFIED${NC}"
        echo -e "${GREEN}${BOLD}========================================${NC}"
        echo ""
        return 0
    fi
}

# -------------------------------------------------------------------
# Prerequisite checks
# -------------------------------------------------------------------

check_prerequisites() {
    log_step "Checking prerequisites..."
    local missing=0

    # Python 3.10+
    if command -v python3 &> /dev/null; then
        local py_version
        py_version="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
        local py_major py_minor
        py_major="$(echo "${py_version}" | cut -d. -f1)"
        py_minor="$(echo "${py_version}" | cut -d. -f2)"
        if [[ "${py_major}" -lt 3 ]] || { [[ "${py_major}" -eq 3 ]] && [[ "${py_minor}" -lt 10 ]]; }; then
            log_error "Python 3.10+ required, found ${py_version}"
            missing=1
        else
            log_info "Python ${py_version} found"
        fi
    else
        log_error "Python 3 is not installed"
        missing=1
    fi

    # tmux (optional — needed for persistent terminal sessions)
    if command -v tmux &> /dev/null; then
        log_info "tmux found"
    else
        log_warn "tmux is not installed — persistent terminal sessions will not work"
        log_warn "Install with: sudo apt install tmux (Debian/Ubuntu) or sudo yum install tmux (RHEL)"
    fi

    if [[ "${missing}" -eq 1 ]]; then
        echo ""
        log_error "Missing prerequisites. Please install them and try again."
        exit 1
    fi

    echo ""
}

# -------------------------------------------------------------------
# Interactive setup
# -------------------------------------------------------------------

write_default_config() {
    local secret_key
    secret_key="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    cat > "${INSTALL_DIR}/config.json" << DEFCONFIG_EOF
{
    "host": "0.0.0.0",
    "port": 5001,
    "favorites": [],
    "remote_hosts": [],
    "auth": {
        "enabled": false,
        "username": "",
        "password_hash": ""
    },
    "ssl_enabled": false,
    "ssl_cert": "",
    "ssl_key": "",
    "allowed_paths": ["/opt"],
    "allow_full_browsing": false,
    "secret_key": "${secret_key}",
    "users": []
}
DEFCONFIG_EOF
    log_info "Created default config.json"
}

interactive_setup() {
    # Check if config already exists
    if [[ -f "${INSTALL_DIR}/config.json" ]]; then
        local overwrite=""
        read -p "$(echo -e "${YELLOW}Config already exists. Reconfigure? [y/N]:${NC} ")" overwrite
        if [[ ! "${overwrite}" =~ ^[Yy]$ ]]; then
            log_info "Keeping existing configuration"
            return 0
        fi
    fi

    echo ""
    echo -e "${BOLD}============================================${NC}"
    echo -e "${BOLD}  Configuration Setup${NC}"
    echo -e "${BOLD}============================================${NC}"
    echo ""

    # --- Port ---
    local cfg_port="5001"
    while true; do
        read -p "$(echo -e "  ${CYAN}Server port${NC} [${BOLD}5001${NC}]: ")" cfg_port
        cfg_port="${cfg_port:-5001}"
        if [[ "${cfg_port}" =~ ^[0-9]+$ ]] && [[ "${cfg_port}" -ge 1 ]] && [[ "${cfg_port}" -le 65535 ]]; then
            break
        fi
        log_error "Invalid port. Enter a number between 1-65535."
    done

    # --- Authentication ---
    local cfg_auth_enabled="true"
    local cfg_username=""
    local cfg_password_hash=""
    local cfg_users_json="[]"

    local auth_answer=""
    read -p "$(echo -e "  ${CYAN}Enable authentication? (recommended)${NC} [${BOLD}Y${NC}/n]: ")" auth_answer
    if [[ "${auth_answer}" =~ ^[Nn]$ ]]; then
        cfg_auth_enabled="false"
    else
        cfg_auth_enabled="true"

        # Username
        read -p "$(echo -e "    ${CYAN}Username${NC} [${BOLD}admin${NC}]: ")" cfg_username
        cfg_username="${cfg_username:-admin}"

        # Password with confirmation
        local cfg_password=""
        while true; do
            read -s -p "$(echo -e "    ${CYAN}Password${NC} (min 8 chars): ")" cfg_password
            echo ""
            if [[ "${#cfg_password}" -lt 8 ]]; then
                log_error "Password must be at least 8 characters."
                continue
            fi
            local cfg_password_confirm=""
            read -s -p "$(echo -e "    ${CYAN}Confirm password${NC}: ")" cfg_password_confirm
            echo ""
            if [[ "${cfg_password}" != "${cfg_password_confirm}" ]]; then
                log_error "Passwords do not match. Try again."
                continue
            fi
            break
        done

        # Hash password using vendored werkzeug
        cfg_password_hash="$(PYTHONPATH="${INSTALL_DIR}/vendor" python3 -c "
from werkzeug.security import generate_password_hash
import sys
print(generate_password_hash(sys.stdin.readline().strip()))
" <<< "${cfg_password}")"

        cfg_users_json="[{\"username\": \"${cfg_username}\", \"password_hash\": \"${cfg_password_hash}\", \"role\": \"admin\"}]"
    fi

    # --- SSL ---
    local cfg_ssl_enabled="false"
    local cfg_ssl_cert=""
    local cfg_ssl_key=""

    local ssl_answer=""
    read -p "$(echo -e "  ${CYAN}Enable HTTPS/SSL?${NC} [y/${BOLD}N${NC}]: ")" ssl_answer
    if [[ "${ssl_answer}" =~ ^[Yy]$ ]]; then
        cfg_ssl_enabled="true"
        echo -e "    ${BOLD}[1]${NC} Auto-generate self-signed certificate"
        echo -e "    ${BOLD}[2]${NC} Provide custom certificate paths"
        local ssl_choice=""
        read -p "$(echo -e "    ${CYAN}Choice${NC} [${BOLD}1${NC}]: ")" ssl_choice
        ssl_choice="${ssl_choice:-1}"

        if [[ "${ssl_choice}" == "2" ]]; then
            while true; do
                read -p "$(echo -e "    ${CYAN}Certificate path${NC}: ")" cfg_ssl_cert
                if [[ -f "${cfg_ssl_cert}" ]]; then
                    break
                fi
                log_error "File not found: ${cfg_ssl_cert}"
            done
            while true; do
                read -p "$(echo -e "    ${CYAN}Private key path${NC}: ")" cfg_ssl_key
                if [[ -f "${cfg_ssl_key}" ]]; then
                    break
                fi
                log_error "File not found: ${cfg_ssl_key}"
            done
        fi
        # Choice 1 (auto-generate) leaves cert/key empty - app.py handles generation
    fi

    # --- Allowed paths ---
    local cfg_allowed_paths="/opt"
    read -p "$(echo -e "  ${CYAN}Allowed project paths${NC} (comma-separated) [${BOLD}/opt${NC}]: ")" cfg_allowed_paths
    cfg_allowed_paths="${cfg_allowed_paths:-/opt}"

    # Convert comma-separated to JSON array
    local paths_json=""
    IFS=',' read -ra path_arr <<< "${cfg_allowed_paths}"
    for i in "${!path_arr[@]}"; do
        local trimmed
        trimmed="$(echo "${path_arr[$i]}" | xargs)"
        if [[ "$i" -gt 0 ]]; then
            paths_json+=", "
        fi
        paths_json+="\"${trimmed}\""
    done

    # --- Full browsing ---
    local cfg_full_browsing="false"
    local browse_answer=""
    read -p "$(echo -e "  ${CYAN}Allow full filesystem browsing?${NC} [y/${BOLD}N${NC}]: ")" browse_answer
    if [[ "${browse_answer}" =~ ^[Yy]$ ]]; then
        cfg_full_browsing="true"
    fi

    echo ""

    # --- Generate secret key ---
    local secret_key
    secret_key="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"

    # --- Write config ---
    log_info "Writing configuration..."

    cat > "${INSTALL_DIR}/config.json" << INTCONFIG_EOF
{
    "host": "0.0.0.0",
    "port": ${cfg_port},
    "favorites": [],
    "remote_hosts": [],
    "auth": {
        "enabled": ${cfg_auth_enabled},
        "username": "${cfg_username}",
        "password_hash": "${cfg_password_hash}"
    },
    "ssl_enabled": ${cfg_ssl_enabled},
    "ssl_cert": "${cfg_ssl_cert}",
    "ssl_key": "${cfg_ssl_key}",
    "allowed_paths": [${paths_json}],
    "allow_full_browsing": ${cfg_full_browsing},
    "secret_key": "${secret_key}",
    "users": ${cfg_users_json}
}
INTCONFIG_EOF

    log_info "Configuration saved"
    echo ""
}

# -------------------------------------------------------------------
# Installation
# -------------------------------------------------------------------

do_install() {
    echo ""
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo -e "${GREEN}${BOLD}  QN Code Assistant Installer v${VERSION}${NC}"
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo ""

    # Step 1: Verify integrity
    log_step "Step 1/5: Verifying file integrity..."
    if ! verify_integrity; then
        exit 1
    fi

    # Step 2: Check prerequisites
    log_step "Step 2/5: Checking prerequisites..."
    check_prerequisites

    # Step 3: Create directories
    log_step "Step 3/5: Creating directories..."
    mkdir -p "${INSTALL_DIR}/sessions"
    mkdir -p "${INSTALL_DIR}/backups"
    mkdir -p "${INSTALL_DIR}/certs"
    log_info "Created directories: sessions/, backups/, certs/"
    echo ""

    # Step 4: Configuration
    log_step "Step 4/5: Configuration..."
    if [[ "${NONINTERACTIVE}" -eq 1 ]]; then
        if [[ ! -f "${INSTALL_DIR}/config.json" ]]; then
            write_default_config
        else
            log_info "config.json already exists, preserving"
        fi
    else
        interactive_setup
    fi

    # Step 5: Set file permissions
    log_step "Step 5/5: Setting file permissions..."

    # Ensure scripts are executable
    chmod 755 "${INSTALL_DIR}/start.sh"
    chmod 755 "${INSTALL_DIR}/maintenance.sh"
    chmod 755 "${INSTALL_DIR}/install.sh"
    if [[ -f "${INSTALL_DIR}/build-installer.sh" ]]; then
        chmod 755 "${INSTALL_DIR}/build-installer.sh"
    fi

    # Restrict config files (contain sensitive data)
    chmod 600 "${INSTALL_DIR}/config.json"
    if [[ -f "${INSTALL_DIR}/usage.json" ]]; then
        chmod 600 "${INSTALL_DIR}/usage.json"
    fi

    # Ensure no world-writable files
    local world_writable
    world_writable="$(find "${INSTALL_DIR}" -maxdepth 3 -perm -o+w -not -path "${INSTALL_DIR}/.git/*" -type f 2>/dev/null || true)"
    if [[ -n "${world_writable}" ]]; then
        log_warn "Removing world-writable permission from files:"
        while IFS= read -r wf; do
            chmod o-w "${wf}"
            log_warn "  Fixed: ${wf}"
        done <<< "${world_writable}"
    fi

    # Restrict directories
    chmod 750 "${INSTALL_DIR}/sessions"
    chmod 750 "${INSTALL_DIR}/backups"
    chmod 750 "${INSTALL_DIR}/certs"

    log_info "File permissions set"
    echo ""

    # Systemd service (optional)
    if [[ -d "/etc/systemd/system" ]]; then
        if [[ "$(id -u)" -eq 0 ]]; then
            cp "${INSTALL_DIR}/qn-code-assistant.service" /etc/systemd/system/qn-code-assistant.service
            systemctl daemon-reload
            systemctl enable qn-code-assistant
            log_info "Systemd service installed and enabled"
            log_info "Start with: sudo systemctl start qn-code-assistant"
        else
            log_warn "Not running as root. To install the systemd service, run:"
            echo "         sudo cp ${INSTALL_DIR}/qn-code-assistant.service /etc/systemd/system/"
            echo "         sudo systemctl daemon-reload"
            echo "         sudo systemctl enable qn-code-assistant"
            echo "         sudo systemctl start qn-code-assistant"
        fi
    else
        log_warn "systemd not detected. Manual service setup required."
    fi

    echo ""

    # Summary
    local ip_addr
    ip_addr="$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")"
    local protocol="http"
    local summary_port="${cfg_port:-5001}"
    if grep -q '"ssl_enabled": true' "${INSTALL_DIR}/config.json" 2>/dev/null; then
        protocol="https"
    fi

    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo -e "${GREEN}${BOLD}  Installation Complete!${NC}"
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo ""
    echo -e "  Version:     ${CYAN}${VERSION}${NC}"
    echo -e "  Install dir: ${CYAN}${INSTALL_DIR}${NC}"
    echo -e "  Access URL:  ${CYAN}${protocol}://${ip_addr}:${summary_port}${NC}"
    echo -e "  Prereqs:     ${CYAN}Python 3.10+ only (deps vendored)${NC}"
    echo ""
    echo -e "  Quick start:"
    echo -e "    ${YELLOW}cd ${INSTALL_DIR} && ./start.sh${NC}"
    echo ""
    echo -e "  Or via systemd:"
    echo -e "    ${YELLOW}sudo systemctl start qn-code-assistant${NC}"
    echo ""
    echo -e "  View logs:"
    echo -e "    ${YELLOW}sudo journalctl -u qn-code-assistant -f${NC}"
    echo ""
}

# -------------------------------------------------------------------
# Uninstall
# -------------------------------------------------------------------

do_uninstall() {
    echo ""
    echo -e "${RED}${BOLD}============================================${NC}"
    echo -e "${RED}${BOLD}  QN Code Assistant - Uninstall${NC}"
    echo -e "${RED}${BOLD}============================================${NC}"
    echo ""

    # Stop and disable service
    if [[ -d "/etc/systemd/system" ]]; then
        if [[ "$(id -u)" -eq 0 ]]; then
            if systemctl is-active --quiet qn-code-assistant 2>/dev/null; then
                log_info "Stopping qn-code-assistant service..."
                systemctl stop qn-code-assistant
            fi
            if systemctl is-enabled --quiet qn-code-assistant 2>/dev/null; then
                log_info "Disabling qn-code-assistant service..."
                systemctl disable qn-code-assistant
            fi
            if [[ -f "/etc/systemd/system/qn-code-assistant.service" ]]; then
                rm -f /etc/systemd/system/qn-code-assistant.service
                systemctl daemon-reload
                log_info "Removed systemd service file"
            fi
        else
            log_warn "Not running as root. To remove the systemd service, run:"
            echo "         sudo systemctl stop qn-code-assistant"
            echo "         sudo systemctl disable qn-code-assistant"
            echo "         sudo rm /etc/systemd/system/qn-code-assistant.service"
            echo "         sudo systemctl daemon-reload"
        fi
    fi

    # Remove __pycache__
    find "${INSTALL_DIR}" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    log_info "Removed __pycache__ directories"

    echo ""
    echo -e "${YELLOW}${BOLD}Note:${NC} The following were preserved:"
    echo "  - config.json (your configuration)"
    echo "  - sessions/ (your session data)"
    echo "  - backups/ (your backups)"
    echo "  - usage.json (usage tracking data)"
    echo "  - vendor/ (vendored dependencies)"
    echo "  - Project source files"
    echo ""
    echo -e "To fully remove everything: ${RED}rm -rf ${INSTALL_DIR}${NC}"
    echo ""
}

# -------------------------------------------------------------------
# Main
# -------------------------------------------------------------------

main() {
    case "${1:-}" in
        --verify-only)
            verify_integrity
            ;;
        --uninstall)
            do_uninstall
            ;;
        --help|-h)
            echo "QN Code Assistant - Secure Self-Verifying Installer v${VERSION}"
            echo ""
            echo "Usage:"
            echo "  ./install.sh                Install with interactive setup (default)"
            echo "  ./install.sh -y             Install with defaults (non-interactive)"
            echo "  ./install.sh --verify-only  Only verify file integrity"
            echo "  ./install.sh --uninstall    Remove service and cleanup"
            echo "  ./install.sh --help         Show this help"
            echo ""
            echo "Self-contained: only requires Python 3.10+ (no pip, no venv, no internet)"
            ;;
        -y|--non-interactive)
            NONINTERACTIVE=1
            do_install
            ;;
        "")
            do_install
            ;;
        *)
            log_error "Unknown option: $1"
            echo "Run ./install.sh --help for usage."
            exit 1
            ;;
    esac
}

main "$@"
INSTALLER_BODY

chmod 755 "${INSTALLER}"

echo ""
echo -e "${GREEN}${BOLD}Installer generated successfully!${NC}"
echo -e "  Output: ${INSTALLER}"
echo -e "  Version: ${VERSION}"
echo -e "  Files tracked: ${#PROJECT_FILES[@]} + vendor/ (${VENDOR_FILE_COUNT} files) + ace/ (${ACE_FILE_COUNT} files)"
echo ""
echo -e "Test with: ${YELLOW}./install.sh --verify-only${NC}"
echo ""
