#!/bin/bash
#
# QN Code Assistant - Secure Self-Verifying Installer
#
# Self-contained installer with vendored Python dependencies.
# Only requires Python 3.8+ on the target system. No pip, no venv, no internet.
#
# Usage:
#   ./install.sh              Install (verify + setup)
#   ./install.sh --verify-only    Only verify file integrity
#   ./install.sh --uninstall      Remove service and cleanup
#
# Generated by build-installer.sh -- DO NOT EDIT MANUALLY
#

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

VERSION="1.5.1"

# SHA-256 hashes baked at build time
declare -A FILE_HASHES=(
    ["app.py"]="d3542979b27994b423c6011ef7c9ed0f1ba98b4d4f7294725ab42f239a1f625c"
    ["static/js/app.js"]="0650a346352809798d890bdc77492b18731e731241d6818b525dd5e2096707c5"
    ["static/css/style.css"]="5fb199bc175bef59b5cb4efa14882975385f7dd443535f575159e1863542b9c8"
    ["templates/index.html"]="80869d43301945df2d1563d2791706b6475b8a86873c93be840eaec78426ddfb"
    ["templates/login.html"]="5e77d824bad5af53a817ea7cf554992cb1d77e2050a41bd0add00880d5454aac"
    ["requirements.txt"]="4122e97cfa01caa3042e3d3b3e35a778a9e658c84a62a31177f19c041785c8d5"
    ["static/manifest.json"]="c2872d517d42875cd02f0dfdb5e9a8d79522097dd1b016450fc3afe59cace431"
    ["static/sw.js"]="dd99f2f9ead0c3efd1067724e76939e297632f3d959f3522cc33c54601373402"
    ["static/icon.svg"]="62f098e754f05bc584ef68b681141961ed172a072bf10ab9e494356df27ce034"
    ["apache-proxy.conf"]="5eab0edd895142e586693d410f82146cea4fd7dc0327c684cbf4b80c65fda248"
    ["maintenance.sh"]="69cb8b8938771c83b810d4736113bb1dfdb4a225d83858eb3e475a284ae0ecdc"
    ["start.sh"]="3c321fffe379a6ce9d1d3b782542e0c69e2348874a7fb5e26826d2f25b5306bc"
    ["qn-code-assistant.service"]="722ebb970d9c40ba4ea95f1424424f0041c4518e774ba8c027d008b6a725e6d4"
)

VENDOR_HASH="1ddb9ad9384df343937a83d208f5f3d7ff743170118973b0f6fcde65e20f3765"
VENDOR_FILE_COUNT="329"
ACE_HASH="13b2cedadef1e3fdadc06bdfdb2be31f26cc89f61a9017ab7c967ca17f54ec73"
ACE_FILE_COUNT="30"

NONINTERACTIVE=0

# -------------------------------------------------------------------
# Utility functions
# -------------------------------------------------------------------

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${CYAN}[STEP]${NC} ${BOLD}$1${NC}"
}

# Determine available sha256 command
detect_sha_cmd() {
    if command -v sha256sum &> /dev/null; then
        echo "sha256sum"
    elif command -v shasum &> /dev/null; then
        echo "shasum -a 256"
    else
        log_error "Neither sha256sum nor shasum found. Cannot verify integrity."
        exit 1
    fi
}

# -------------------------------------------------------------------
# Integrity verification
# -------------------------------------------------------------------

verify_integrity() {
    local sha_cmd
    sha_cmd="$(detect_sha_cmd)"
    local failed=0
    local checked=0
    local tampered_files=()

    echo ""
    echo -e "${BOLD}========================================${NC}"
    echo -e "${BOLD}  File Integrity Verification${NC}"
    echo -e "${BOLD}========================================${NC}"
    echo ""

    # Verify individual project files
    for file in "${!FILE_HASHES[@]}"; do
        local expected="${FILE_HASHES[${file}]}"
        local filepath="${INSTALL_DIR}/${file}"

        if [[ ! -f "${filepath}" ]]; then
            log_error "Missing file: ${file}"
            tampered_files+=("${file} (MISSING)")
            failed=1
            continue
        fi

        local actual
        actual="$($sha_cmd "${filepath}" | awk '{print $1}')"

        if [[ "${actual}" != "${expected}" ]]; then
            log_error "Hash mismatch: ${file}"
            echo "         Expected: ${expected}"
            echo "         Actual:   ${actual}"
            tampered_files+=("${file}")
            failed=1
        else
            log_info "Verified: ${file}"
        fi

        checked=$((checked + 1))
    done

    # Verify vendor/ directory
    local vendor_dir="${INSTALL_DIR}/vendor"
    if [[ ! -d "${vendor_dir}" ]]; then
        log_error "Missing directory: vendor/"
        tampered_files+=("vendor/ (MISSING)")
        failed=1
    else
        local actual_count
        actual_count="$(find "${vendor_dir}" -type f -not -path '*/__pycache__/*' | wc -l)"
        local actual_hash
        actual_hash="$(cd "${INSTALL_DIR}" && find vendor/ -type f -not -path '*/__pycache__/*' -print0 | sort -z | xargs -0 $sha_cmd | $sha_cmd | awk '{print $1}')"

        if [[ "${actual_hash}" != "${VENDOR_HASH}" ]]; then
            log_error "Hash mismatch: vendor/ (${actual_count} files)"
            echo "         Expected: ${VENDOR_HASH}"
            echo "         Actual:   ${actual_hash}"
            tampered_files+=("vendor/")
            failed=1
        else
            log_info "Verified: vendor/ (${actual_count} files)"
        fi
        checked=$((checked + 1))
    fi

    # Verify static/js/ace/ directory
    local ace_dir="${INSTALL_DIR}/static/js/ace"
    if [[ ! -d "${ace_dir}" ]]; then
        log_error "Missing directory: static/js/ace/"
        tampered_files+=("static/js/ace/ (MISSING)")
        failed=1
    else
        local ace_actual_count
        ace_actual_count="$(find "${ace_dir}" -type f -not -path '*/__pycache__/*' | wc -l)"
        local ace_actual_hash
        ace_actual_hash="$(cd "${INSTALL_DIR}" && find static/js/ace/ -type f -not -path '*/__pycache__/*' -print0 | sort -z | xargs -0 $sha_cmd | $sha_cmd | awk '{print $1}')"

        if [[ "${ace_actual_hash}" != "${ACE_HASH}" ]]; then
            log_error "Hash mismatch: static/js/ace/ (${ace_actual_count} files)"
            echo "         Expected: ${ACE_HASH}"
            echo "         Actual:   ${ace_actual_hash}"
            tampered_files+=("static/js/ace/")
            failed=1
        else
            log_info "Verified: static/js/ace/ (${ace_actual_count} files)"
        fi
        checked=$((checked + 1))
    fi

    echo ""

    if [[ "${failed}" -eq 1 ]]; then
        echo -e "${RED}${BOLD}========================================${NC}"
        echo -e "${RED}${BOLD}  INTEGRITY CHECK FAILED${NC}"
        echo -e "${RED}${BOLD}========================================${NC}"
        echo ""
        echo -e "${RED}The following files have been tampered with or are missing:${NC}"
        for tf in "${tampered_files[@]}"; do
            echo -e "  ${RED}- ${tf}${NC}"
        done
        echo ""
        echo -e "${RED}Installation aborted. Files do not match the expected checksums.${NC}"
        echo -e "${RED}Re-obtain the original project files before installing.${NC}"
        return 1
    else
        echo -e "${GREEN}${BOLD}========================================${NC}"
        echo -e "${GREEN}${BOLD}  ALL ${checked} ITEMS VERIFIED${NC}"
        echo -e "${GREEN}${BOLD}========================================${NC}"
        echo ""
        return 0
    fi
}

# -------------------------------------------------------------------
# Prerequisite checks
# -------------------------------------------------------------------

check_prerequisites() {
    log_step "Checking prerequisites..."
    local missing=0

    # Python 3.8+
    if command -v python3 &> /dev/null; then
        local py_version
        py_version="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
        local py_major py_minor
        py_major="$(echo "${py_version}" | cut -d. -f1)"
        py_minor="$(echo "${py_version}" | cut -d. -f2)"
        if [[ "${py_major}" -lt 3 ]] || { [[ "${py_major}" -eq 3 ]] && [[ "${py_minor}" -lt 8 ]]; }; then
            log_error "Python 3.8+ required, found ${py_version}"
            missing=1
        else
            log_info "Python ${py_version} found"
        fi
    else
        log_error "Python 3 is not installed"
        missing=1
    fi

    # tmux (optional — needed for persistent terminal sessions)
    if command -v tmux &> /dev/null; then
        log_info "tmux found"
    else
        log_warn "tmux is not installed — persistent terminal sessions will not work"
        log_warn "Install with: sudo apt install tmux (Debian/Ubuntu) or sudo yum install tmux (RHEL)"
    fi

    if [[ "${missing}" -eq 1 ]]; then
        echo ""
        log_error "Missing prerequisites. Please install them and try again."
        exit 1
    fi

    echo ""
}

# -------------------------------------------------------------------
# Interactive setup
# -------------------------------------------------------------------

write_default_config() {
    local secret_key
    secret_key="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    cat > "${INSTALL_DIR}/config.json" << DEFCONFIG_EOF
{
    "host": "0.0.0.0",
    "port": 5001,
    "favorites": [],
    "remote_hosts": [],
    "auth": {
        "enabled": false,
        "username": "",
        "password_hash": ""
    },
    "ssl_enabled": false,
    "ssl_cert": "",
    "ssl_key": "",
    "allowed_paths": ["/opt"],
    "allow_full_browsing": false,
    "secret_key": "${secret_key}",
    "users": []
}
DEFCONFIG_EOF
    log_info "Created default config.json"
}

interactive_setup() {
    # Check if config already exists
    if [[ -f "${INSTALL_DIR}/config.json" ]]; then
        local overwrite=""
        read -p "$(echo -e "${YELLOW}Config already exists. Reconfigure? [y/N]:${NC} ")" overwrite
        if [[ ! "${overwrite}" =~ ^[Yy]$ ]]; then
            log_info "Keeping existing configuration"
            return 0
        fi
    fi

    echo ""
    echo -e "${BOLD}============================================${NC}"
    echo -e "${BOLD}  Configuration Setup${NC}"
    echo -e "${BOLD}============================================${NC}"
    echo ""

    # --- Port ---
    local cfg_port="5001"
    while true; do
        read -p "$(echo -e "  ${CYAN}Server port${NC} [${BOLD}5001${NC}]: ")" cfg_port
        cfg_port="${cfg_port:-5001}"
        if [[ "${cfg_port}" =~ ^[0-9]+$ ]] && [[ "${cfg_port}" -ge 1 ]] && [[ "${cfg_port}" -le 65535 ]]; then
            break
        fi
        log_error "Invalid port. Enter a number between 1-65535."
    done

    # --- Authentication ---
    local cfg_auth_enabled="true"
    local cfg_username=""
    local cfg_password_hash=""
    local cfg_users_json="[]"

    local auth_answer=""
    read -p "$(echo -e "  ${CYAN}Enable authentication? (recommended)${NC} [${BOLD}Y${NC}/n]: ")" auth_answer
    if [[ "${auth_answer}" =~ ^[Nn]$ ]]; then
        cfg_auth_enabled="false"
    else
        cfg_auth_enabled="true"

        # Username
        read -p "$(echo -e "    ${CYAN}Username${NC} [${BOLD}admin${NC}]: ")" cfg_username
        cfg_username="${cfg_username:-admin}"

        # Password with confirmation
        local cfg_password=""
        while true; do
            read -s -p "$(echo -e "    ${CYAN}Password${NC} (min 4 chars): ")" cfg_password
            echo ""
            if [[ "${#cfg_password}" -lt 4 ]]; then
                log_error "Password must be at least 4 characters."
                continue
            fi
            local cfg_password_confirm=""
            read -s -p "$(echo -e "    ${CYAN}Confirm password${NC}: ")" cfg_password_confirm
            echo ""
            if [[ "${cfg_password}" != "${cfg_password_confirm}" ]]; then
                log_error "Passwords do not match. Try again."
                continue
            fi
            break
        done

        # Hash password using vendored werkzeug
        cfg_password_hash="$(PYTHONPATH="${INSTALL_DIR}/vendor" python3 -c "
from werkzeug.security import generate_password_hash
import sys
print(generate_password_hash(sys.stdin.readline().strip()))
" <<< "${cfg_password}")"

        cfg_users_json="[{\"username\": \"${cfg_username}\", \"password_hash\": \"${cfg_password_hash}\", \"role\": \"admin\"}]"
    fi

    # --- SSL ---
    local cfg_ssl_enabled="false"
    local cfg_ssl_cert=""
    local cfg_ssl_key=""

    local ssl_answer=""
    read -p "$(echo -e "  ${CYAN}Enable HTTPS/SSL?${NC} [y/${BOLD}N${NC}]: ")" ssl_answer
    if [[ "${ssl_answer}" =~ ^[Yy]$ ]]; then
        cfg_ssl_enabled="true"
        echo -e "    ${BOLD}[1]${NC} Auto-generate self-signed certificate"
        echo -e "    ${BOLD}[2]${NC} Provide custom certificate paths"
        local ssl_choice=""
        read -p "$(echo -e "    ${CYAN}Choice${NC} [${BOLD}1${NC}]: ")" ssl_choice
        ssl_choice="${ssl_choice:-1}"

        if [[ "${ssl_choice}" == "2" ]]; then
            while true; do
                read -p "$(echo -e "    ${CYAN}Certificate path${NC}: ")" cfg_ssl_cert
                if [[ -f "${cfg_ssl_cert}" ]]; then
                    break
                fi
                log_error "File not found: ${cfg_ssl_cert}"
            done
            while true; do
                read -p "$(echo -e "    ${CYAN}Private key path${NC}: ")" cfg_ssl_key
                if [[ -f "${cfg_ssl_key}" ]]; then
                    break
                fi
                log_error "File not found: ${cfg_ssl_key}"
            done
        fi
        # Choice 1 (auto-generate) leaves cert/key empty - app.py handles generation
    fi

    # --- Allowed paths ---
    local cfg_allowed_paths="/opt"
    read -p "$(echo -e "  ${CYAN}Allowed project paths${NC} (comma-separated) [${BOLD}/opt${NC}]: ")" cfg_allowed_paths
    cfg_allowed_paths="${cfg_allowed_paths:-/opt}"

    # Convert comma-separated to JSON array
    local paths_json=""
    IFS=',' read -ra path_arr <<< "${cfg_allowed_paths}"
    for i in "${!path_arr[@]}"; do
        local trimmed
        trimmed="$(echo "${path_arr[$i]}" | xargs)"
        if [[ "$i" -gt 0 ]]; then
            paths_json+=", "
        fi
        paths_json+="\"${trimmed}\""
    done

    # --- Full browsing ---
    local cfg_full_browsing="false"
    local browse_answer=""
    read -p "$(echo -e "  ${CYAN}Allow full filesystem browsing?${NC} [y/${BOLD}N${NC}]: ")" browse_answer
    if [[ "${browse_answer}" =~ ^[Yy]$ ]]; then
        cfg_full_browsing="true"
    fi

    echo ""

    # --- Generate secret key ---
    local secret_key
    secret_key="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"

    # --- Write config ---
    log_info "Writing configuration..."

    cat > "${INSTALL_DIR}/config.json" << INTCONFIG_EOF
{
    "host": "0.0.0.0",
    "port": ${cfg_port},
    "favorites": [],
    "remote_hosts": [],
    "auth": {
        "enabled": ${cfg_auth_enabled},
        "username": "${cfg_username}",
        "password_hash": "${cfg_password_hash}"
    },
    "ssl_enabled": ${cfg_ssl_enabled},
    "ssl_cert": "${cfg_ssl_cert}",
    "ssl_key": "${cfg_ssl_key}",
    "allowed_paths": [${paths_json}],
    "allow_full_browsing": ${cfg_full_browsing},
    "secret_key": "${secret_key}",
    "users": ${cfg_users_json}
}
INTCONFIG_EOF

    log_info "Configuration saved"
    echo ""
}

# -------------------------------------------------------------------
# Installation
# -------------------------------------------------------------------

do_install() {
    echo ""
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo -e "${GREEN}${BOLD}  QN Code Assistant Installer v${VERSION}${NC}"
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo ""

    # Step 1: Verify integrity
    log_step "Step 1/5: Verifying file integrity..."
    if ! verify_integrity; then
        exit 1
    fi

    # Step 2: Check prerequisites
    log_step "Step 2/5: Checking prerequisites..."
    check_prerequisites

    # Step 3: Create directories
    log_step "Step 3/5: Creating directories..."
    mkdir -p "${INSTALL_DIR}/sessions"
    mkdir -p "${INSTALL_DIR}/backups"
    mkdir -p "${INSTALL_DIR}/certs"
    log_info "Created directories: sessions/, backups/, certs/"
    echo ""

    # Step 4: Configuration
    log_step "Step 4/5: Configuration..."
    if [[ "${NONINTERACTIVE}" -eq 1 ]]; then
        if [[ ! -f "${INSTALL_DIR}/config.json" ]]; then
            write_default_config
        else
            log_info "config.json already exists, preserving"
        fi
    else
        interactive_setup
    fi

    # Step 5: Set file permissions
    log_step "Step 5/5: Setting file permissions..."

    # Ensure scripts are executable
    chmod 755 "${INSTALL_DIR}/start.sh"
    chmod 755 "${INSTALL_DIR}/maintenance.sh"
    chmod 755 "${INSTALL_DIR}/install.sh"
    if [[ -f "${INSTALL_DIR}/build-installer.sh" ]]; then
        chmod 755 "${INSTALL_DIR}/build-installer.sh"
    fi

    # Restrict config files (contain sensitive data)
    chmod 600 "${INSTALL_DIR}/config.json"
    if [[ -f "${INSTALL_DIR}/usage.json" ]]; then
        chmod 600 "${INSTALL_DIR}/usage.json"
    fi

    # Ensure no world-writable files
    local world_writable
    world_writable="$(find "${INSTALL_DIR}" -maxdepth 3 -perm -o+w -not -path "${INSTALL_DIR}/.git/*" -type f 2>/dev/null || true)"
    if [[ -n "${world_writable}" ]]; then
        log_warn "Removing world-writable permission from files:"
        while IFS= read -r wf; do
            chmod o-w "${wf}"
            log_warn "  Fixed: ${wf}"
        done <<< "${world_writable}"
    fi

    # Restrict directories
    chmod 750 "${INSTALL_DIR}/sessions"
    chmod 750 "${INSTALL_DIR}/backups"
    chmod 750 "${INSTALL_DIR}/certs"

    log_info "File permissions set"
    echo ""

    # Systemd service (optional)
    if [[ -d "/etc/systemd/system" ]]; then
        if [[ "$(id -u)" -eq 0 ]]; then
            cp "${INSTALL_DIR}/qn-code-assistant.service" /etc/systemd/system/qn-code-assistant.service
            systemctl daemon-reload
            systemctl enable qn-code-assistant
            log_info "Systemd service installed and enabled"
            log_info "Start with: sudo systemctl start qn-code-assistant"
        else
            log_warn "Not running as root. To install the systemd service, run:"
            echo "         sudo cp ${INSTALL_DIR}/qn-code-assistant.service /etc/systemd/system/"
            echo "         sudo systemctl daemon-reload"
            echo "         sudo systemctl enable qn-code-assistant"
            echo "         sudo systemctl start qn-code-assistant"
        fi
    else
        log_warn "systemd not detected. Manual service setup required."
    fi

    echo ""

    # Summary
    local ip_addr
    ip_addr="$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")"
    local protocol="http"
    local summary_port="${cfg_port:-5001}"
    if grep -q '"ssl_enabled": true' "${INSTALL_DIR}/config.json" 2>/dev/null; then
        protocol="https"
    fi

    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo -e "${GREEN}${BOLD}  Installation Complete!${NC}"
    echo -e "${GREEN}${BOLD}============================================${NC}"
    echo ""
    echo -e "  Version:     ${CYAN}${VERSION}${NC}"
    echo -e "  Install dir: ${CYAN}${INSTALL_DIR}${NC}"
    echo -e "  Access URL:  ${CYAN}${protocol}://${ip_addr}:${summary_port}${NC}"
    echo -e "  Prereqs:     ${CYAN}Python 3.8+ only (deps vendored)${NC}"
    echo ""
    echo -e "  Quick start:"
    echo -e "    ${YELLOW}cd ${INSTALL_DIR} && ./start.sh${NC}"
    echo ""
    echo -e "  Or via systemd:"
    echo -e "    ${YELLOW}sudo systemctl start qn-code-assistant${NC}"
    echo ""
    echo -e "  View logs:"
    echo -e "    ${YELLOW}sudo journalctl -u qn-code-assistant -f${NC}"
    echo ""
}

# -------------------------------------------------------------------
# Uninstall
# -------------------------------------------------------------------

do_uninstall() {
    echo ""
    echo -e "${RED}${BOLD}============================================${NC}"
    echo -e "${RED}${BOLD}  QN Code Assistant - Uninstall${NC}"
    echo -e "${RED}${BOLD}============================================${NC}"
    echo ""

    # Stop and disable service
    if [[ -d "/etc/systemd/system" ]]; then
        if [[ "$(id -u)" -eq 0 ]]; then
            if systemctl is-active --quiet qn-code-assistant 2>/dev/null; then
                log_info "Stopping qn-code-assistant service..."
                systemctl stop qn-code-assistant
            fi
            if systemctl is-enabled --quiet qn-code-assistant 2>/dev/null; then
                log_info "Disabling qn-code-assistant service..."
                systemctl disable qn-code-assistant
            fi
            if [[ -f "/etc/systemd/system/qn-code-assistant.service" ]]; then
                rm -f /etc/systemd/system/qn-code-assistant.service
                systemctl daemon-reload
                log_info "Removed systemd service file"
            fi
        else
            log_warn "Not running as root. To remove the systemd service, run:"
            echo "         sudo systemctl stop qn-code-assistant"
            echo "         sudo systemctl disable qn-code-assistant"
            echo "         sudo rm /etc/systemd/system/qn-code-assistant.service"
            echo "         sudo systemctl daemon-reload"
        fi
    fi

    # Remove __pycache__
    find "${INSTALL_DIR}" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    log_info "Removed __pycache__ directories"

    echo ""
    echo -e "${YELLOW}${BOLD}Note:${NC} The following were preserved:"
    echo "  - config.json (your configuration)"
    echo "  - sessions/ (your session data)"
    echo "  - backups/ (your backups)"
    echo "  - usage.json (usage tracking data)"
    echo "  - vendor/ (vendored dependencies)"
    echo "  - Project source files"
    echo ""
    echo -e "To fully remove everything: ${RED}rm -rf ${INSTALL_DIR}${NC}"
    echo ""
}

# -------------------------------------------------------------------
# Main
# -------------------------------------------------------------------

main() {
    case "${1:-}" in
        --verify-only)
            verify_integrity
            ;;
        --uninstall)
            do_uninstall
            ;;
        --help|-h)
            echo "QN Code Assistant - Secure Self-Verifying Installer v${VERSION}"
            echo ""
            echo "Usage:"
            echo "  ./install.sh                Install with interactive setup (default)"
            echo "  ./install.sh -y             Install with defaults (non-interactive)"
            echo "  ./install.sh --verify-only  Only verify file integrity"
            echo "  ./install.sh --uninstall    Remove service and cleanup"
            echo "  ./install.sh --help         Show this help"
            echo ""
            echo "Self-contained: only requires Python 3.8+ (no pip, no venv, no internet)"
            ;;
        -y|--non-interactive)
            NONINTERACTIVE=1
            do_install
            ;;
        "")
            do_install
            ;;
        *)
            log_error "Unknown option: $1"
            echo "Run ./install.sh --help for usage."
            exit 1
            ;;
    esac
}

main "$@"
